name: etl-final

services:

  mongo:
    image: mongo
    restart: always
    container_name: ETL_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
#      - ./project_data/mongo_data/:/data/db/
      - ./project_data/mongo_data/mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  mongo-express:
    image: mongo-express
    restart: always
    container_name: ETL_mongo_ui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${ME_CONFIG_MONGODB_ADMINPASSWORD}"
      ME_CONFIG_MONGODB_URL: "${ME_CONFIG_MONGODB_URL}"
    env_file:
      - ./.env
    depends_on:
      - mongo

  postgresql:
    image: postgres:17.4-bookworm
    restart: always
    container_name: ETL_postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./project_data/postgres_data/:/var/lib/postgres/data
      - ./project_data/postgres_data/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: ETL_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
#    volumes:
#      - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "6060:80"
    env_file:
      - ./.env
    depends_on:
      - postgresql

  airflow_webserver:
    build: ./project_data/airflow/
    restart: always
    container_name: ETL_airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: "${AIRFLOW__CORE__EXECUTOR}"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}"
      AIRFLOW__CORE__LOG_LEVEL: INFO
      AIRFLOW__CORE__LOGGING_LEVEL: INFO
      GUNICORN_CMD_ARGS: "--access-logfile - --error-logfile -"
    volumes:
      - ./project_data/airflow/dags:/opt/airflow/dags
      - ./project_data/airflow/logs:/opt/airflow/logs
      - ./project_data/airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - postgresql
    deploy:
      resources:
        limits:
          memory: 2g  # увеличиваем лимит памяти
          cpus: '1.0'
        reservations:
          memory: 1g
          cpus: '0.5'
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com &&
               airflow webserver"

  airflow_scheduler:
    build: ./project_data/airflow/
    restart: always
    container_name: ETL_airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: "${AIRFLOW__CORE__EXECUTOR}"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}"
      AIRFLOW__CORE__LOG_LEVEL: INFO
      AIRFLOW__CORE__LOGGING_LEVEL: INFO
      GUNICORN_CMD_ARGS: "--access-logfile - --error-logfile -"
    volumes:
      - ./project_data/airflow/dags:/opt/airflow/dags
      - ./project_data/airflow/logs:/opt/airflow/logs
      - ./project_data/airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgresql
    command: >
      bash -c "airflow db init && airflow scheduler"
